// Generated by CoffeeScript 1.6.1
(function() {
  var assembot, loadOptions, loadTargets, log, notify, _, _ref;

  _ref = require('../index'), assembot = _ref.assembot, _ = _ref._, loadTargets = _ref.loadTargets, loadOptions = _ref.loadOptions;

  log = require('../log');

  notify = require('../notify');

  module.exports = function(cli, pkg, init_logging) {
    return cli.option('-t, --target <filepath>', 'build specified target only').command('build').description('Builds target package(s)').action(function() {
      var all_targets, buildIt, options, opts, target, targets;
      init_logging();
      options = loadOptions();
      all_targets = loadTargets();
      targets = [];
      if (cli.target != null) {
        target = all_targets[cli.target];
        if (target == null) {
          log.say("Target '" + cli.target + "' not found.");
          return;
        }
        all_targets = {};
        all_targets[cli.target] = target;
      }
      for (target in all_targets) {
        opts = all_targets[target];
        targets.push({
          target: target,
          opts: opts
        });
      }
      buildIt = function() {
        var bot, _ref1;
        if (targets.length === 0) {
          notify.emit('done', options);
          return log.info("Done");
        } else {
          _ref1 = targets.shift(), target = _ref1.target, opts = _ref1.opts;
          log.debug("Target:", target);
          log.debug("Configuration:");
          log.debug(opts);
          bot = assembot(target, opts);
          return bot.build().then(buildIt);
        }
      };
      return buildIt();
    });
  };

}).call(this);
