// Generated by CoffeeScript 1.6.1
(function() {
  var build_project, cat, cd, defaults, exec, fgen, loadOptions, log, mkdir, path, spawn, test, _, _ref;

  require('coffee-script');

  _ = require('../util');

  log = require('../log');

  defaults = require('../defaults');

  path = require('path');

  fgen = require('fgen');

  spawn = require('child_process').spawn;

  _ref = require('shelljs'), test = _ref.test, cat = _ref.cat, cd = _ref.cd, mkdir = _ref.mkdir, exec = _ref.exec;

  loadOptions = require('../index').loadOptions;

  build_project = function(name) {
    var projectpath, templatepath;
    projectpath = path.resolve("./" + name);
    if (test('-e', projectpath)) {
      log.say("" + name + " already exists at this location!");
      return;
    }
    console.log("Creating new project:", name);
    templatepath = path.resolve(path.join(__dirname, '../../', 'template'));
    return fgen.createGenerator(templatepath, function(err, generator) {
      if (err != null) {
        throw err;
      }
      generator.context = {
        name: name,
        version: '1.0.0'
      };
      return generator.generateAll(projectpath, function(err) {
        if (err != null) {
          return log.error(err);
        } else {
          cd(projectpath);
          exec("npm install");
          return log.say("Done.");
        }
      });
    });
  };

  module.exports = function(cli, pkg, init_logging) {
    return cli.command('new').description("Creates a new project").action(function(name) {
      init_logging();
      if (process.argv.length < 4) {
        log.say("I am an advanced Bot, yes. But my telepathic circuits aren't ready yet.\n");
        log.say("Please enter a project name!");
        return;
      }
      return build_project(name);
    });
  };

}).call(this);
