// Generated by CoffeeScript 1.6.1
(function() {
  var assembot, defaults, loadOptions, loadTargets, log, server, _, _ref;

  require('coffee-script');

  log = require('../log');

  server = require('../server');

  defaults = require('../defaults');

  _ref = require('../index'), assembot = _ref.assembot, _ = _ref._, loadTargets = _ref.loadTargets, loadOptions = _ref.loadOptions;

  module.exports = function(cli, pkg) {
    return cli.option('-p, --port <n>', 'server port', parseInt).command('serve').description('Starts dev server').action(function() {
      var bot_list, options, target;
      log.info('');
      bot_list = (function() {
        var _ref1, _results;
        _ref1 = loadTargets();
        _results = [];
        for (target in _ref1) {
          options = _ref1[target];
          _results.push(assembot(target, options));
        }
        return _results;
      })();
      options = _.defaults(loadOptions(), {
        http: {
          port: cli.port
        }
      }, defaults.options);
      return server.start(bot_list, options);
    });
  };

}).call(this);
