// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(assembot) {
    var log, processor;
    processor = assembot.processor, log = assembot.log;
    return assembot.before('write', function(bot) {
      var header, output;
      if (!((bot.options.header != null) && bot.options.addHeader)) {
        return;
      }
      switch (bot.target) {
        case 'js':
        case 'css':
          log.debug("Adding header...");
          header = processor.replaceTokens(bot.options.header, {});
          log.trace(header);
          output = "" + header + "\n" + bot.content;
          return bot.content = output;
      }
    });
  };

}).call(this);
