// Generated by CoffeeScript 1.5.0
(function() {
  var Assembler, assembler, defaults, packager, path, _;

  _ = require('./util');

  path = require('path');

  defaults = require('./defaults');

  packager = require('./packager');

  Assembler = (function() {

    function Assembler(target) {
      this.target = target;
    }

    Assembler.prototype["package"] = function(resources, options, callback) {
      var _ref;
      _ref = _.validateOptionsCallback(options, callback), options = _ref[0], callback = _ref[1];
      if (_.type(resources) !== 'array') {
        resources = resources.forTarget(this.target);
      }
      packager.build(this.target, resources, options, callback);
      return this;
    };

    return Assembler;

  })();

  assembler = function(target, resources, options, callback) {
    var asm;
    asm = new Assembler(target);
    return asm["package"](resources, options, callback);
  };

  module.exports = {
    Assembler: Assembler,
    assembler: assembler
  };

}).call(this);
