// Generated by CoffeeScript 1.6.1
(function() {
  var Assembler, EventEmitter, ResourceList, defaults, packager, path, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require('./util');

  path = require('path');

  EventEmitter = require('events').EventEmitter;

  ResourceList = require('./resources').ResourceList;

  defaults = require('./defaults');

  packager = require('./packager');

  Assembler = (function(_super) {

    __extends(Assembler, _super);

    function Assembler(resources) {
      this.resources = resources;
    }

    Assembler.prototype["package"] = function(type, options, callback) {
      var _ref;
      _ref = _.validateOptionsCallback(options, callback), options = _ref[0], callback = _ref[1];
      switch (type) {
        case 'js':
          packager.js(this.resources, options, callback);
          break;
        case 'css':
          packager.css(this.resources, options, callback);
          break;
        default:
          callback(new Error("Unknown package type '" + type + "'"));
      }
      return this;
    };

    return Assembler;

  })(EventEmitter);

  module.exports = {
    Assembler: Assembler
  };

}).call(this);
