// Generated by CoffeeScript 1.6.1
(function() {
  var Assembler, Bot, ResourceList, defaults, fs, path, _;

  _ = require('./util');

  fs = require('fs');

  path = require('path');

  defaults = require('./defaults');

  Assembler = require('./assembler').Assembler;

  ResourceList = require('./resources').ResourceList;

  Bot = (function() {

    function Bot(source, options) {
      this.source = source;
      this.options = options != null ? options : {};
      this.source = path.resolve(this.source);
      this.resources = new ResourceList(this.source);
      this.assembler = new Assembler(this.resources);
      _.defaults(this.options, defaults.options);
    }

    Bot.prototype.get = function(key) {
      return this.options[key];
    };

    Bot.prototype.set = function(keyOrHash, value) {
      var key, val, _results;
      if (typeof keyOrHash === 'string') {
        return this.options[keyOrHash] = value;
      } else {
        _results = [];
        for (key in keyOrHash) {
          val = keyOrHash[key];
          _results.push(this.options[key] = val);
        }
        return _results;
      }
    };

    Bot.prototype.build = function(target, callback) {
      var _this = this;
      return this.resources.scan(function(err) {
        if (err != null) {
          return callback(err);
        }
        return _this.assembler["package"](target, function(err, content) {
          return callback(err, content);
        });
      });
    };

    Bot.prototype.rebuild = Bot.prototype.build;

    return Bot;

  })();

  module.exports = {
    Bot: Bot
  };

}).call(this);
