// Generated by CoffeeScript 1.6.1
(function() {
  var Bot, assembler, defaults, echo, fs, log, packager, path, processor, resourcelist, _;

  _ = require('./util');

  fs = require('fs');

  path = require('path');

  defaults = require('./defaults');

  log = require('./log');

  packager = require('./packager');

  processor = require('./processor');

  echo = require('shelljs').echo;

  assembler = require('./assembler').assembler;

  resourcelist = require('./resources').resourcelist;

  Bot = (function() {

    function Bot(output, options) {
      this.output = output;
      this.options = options != null ? options : {};
      if (this.options.source == null) {
        throw new Error("Options must specify source dir!");
      }
      _.defaults(this.options, defaults.options);
      this.output = path.resolve(this.output);
      this.source = path.resolve(this.options.source);
      this.target = processor.targetOf(this.output);
    }

    Bot.prototype.build = function(callback) {
      var resources,
        _this = this;
      resources = resourcelist(this.source).forTarget(this.target);
      return processor.render(resources, this.options, function(err) {
        return assembler(_this.target, resources, _this.options, function(err, content) {
          if (callback != null) {
            return callback(err, content);
          } else {
            if (err != null) {
              throw err;
            }
            log.info("Saving to", _this.output);
            return content.to(_this.output);
          }
        });
      });
    };

    Bot.prototype.rebuild = Bot.prototype.build;

    return Bot;

  })();

  module.exports = {
    Bot: Bot
  };

}).call(this);
