// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = {
    options: {
      header: "/* Assembled by AssemBot {%- assembot.version -%} */",
      sourceMap: false,
      minify: 0,
      ident: 'require',
      autoLoad: null,
      replaceTokens: true,
      coffee: {
        bare: true
      },
      http: {
        port: 8080,
        paths: {
          '/': './public',
          '/components': './components'
        }
      }
    },
    targets: {
      "public/app.js": {
        source: './source'
      },
      "public/app.css": {
        source: './source'
      }
    }
  };

}).call(this);
