// Generated by CoffeeScript 1.5.0

/*

Stages:

  - Content tree generation
  - Preprocess (unshift user added preprocessors)
  - Process (transpile)
  - Postprocess (?)
  - Assemble (build into commonjs library or single css file)
  - Minify
*/


(function() {
  var Assembler, Bot, Resource, ResourceList, assembot, defaults, _, _ref;

  defaults = require('./defaults');

  _ = require('./util');

  Assembler = require('./assembler').Assembler;

  Bot = require('./bot').Bot;

  _ref = require('./resources'), Resource = _ref.Resource, ResourceList = _ref.ResourceList;

  /* Usage:
    bot= assembot('./source')
    bot.build minify:yes, -> console.log 'done'
  */


  assembot = function(source, options) {
    if (options == null) {
      options = {};
    }
    return new Bot(source, options);
  };

  module.exports = {
    assembot: assembot,
    defaults: defaults,
    _: _,
    Assembler: Assembler,
    Resource: Resource,
    ResourceList: ResourceList,
    Bot: Bot
  };

}).call(this);
