// Generated by CoffeeScript 1.6.1
(function() {
  var Bot, assembler, assembot, defaults, loadFirstLocalPackage, loadOptions, loadTargets, log, packager, path, processor, project_root, resourcelist, _,
    __slice = [].slice;

  log = require('./log');

  defaults = require('./defaults');

  _ = require('./util');

  path = require('path');

  packager = require('./packager');

  processor = require('./processor');

  project_root = process.cwd();

  resourcelist = require('./resources').resourcelist;

  assembler = require('./assembler').assembler;

  Bot = require('./bot').Bot;

  loadFirstLocalPackage = function() {
    var data, name, names, _i, _len;
    names = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    for (_i = 0, _len = names.length; _i < _len; _i++) {
      name = names[_i];
      try {
        data = require("" + project_root + path.sep + name);
        if (data.assembot != null) {
          log.debug("Loaded " + name + ".json");
          return data.assembot;
        } else {
          throw new Error("No Assembot block");
        }
      } catch (ex) {
        log.debug("No '" + name + ".json' file found!");
      }
    }
    log.debug("No configuration found, using defaults!");
    return defaults;
  };

  loadTargets = function() {
    var nfo, options, opts, src_targets, targets, tgt, tgt_opts, _ref, _ref1;
    nfo = loadFirstLocalPackage('package', 'component', 'build', 'assembot');
    options = (_ref = nfo.options) != null ? _ref : defaults.options;
    src_targets = (_ref1 = nfo.targets) != null ? _ref1 : defaults.targets;
    targets = {};
    for (tgt in src_targets) {
      opts = src_targets[tgt];
      tgt_opts = _.defaults({}, opts, options, defaults.options);
      targets[tgt] = tgt_opts;
    }
    return targets;
  };

  loadOptions = function() {
    var nfo, _ref;
    nfo = loadFirstLocalPackage('package', 'component', 'build', 'assembot');
    return (_ref = nfo.options) != null ? _ref : defaults.options;
  };

  assembot = function(target, options) {
    if (options == null) {
      options = {};
    }
    return new Bot(target, options);
  };

  module.exports = {
    assembot: assembot,
    defaults: defaults,
    assembler: assembler,
    resourcelist: resourcelist,
    loadTargets: loadTargets,
    packager: packager,
    processor: processor,
    loadOptions: loadOptions
  };

}).call(this);
