// Generated by CoffeeScript 1.6.1
(function() {
  var debug, error, info, level, log_level, say, trace;

  log_level = 1;

  level = function(lvl) {
    if (lvl != null) {
      log_level = lvl;
    }
    return log_level;
  };

  say = function() {
    return console.log.apply(console, arguments);
  };

  info = function() {
    if (log_level < 1) {
      return;
    }
    return console.log.apply(console, arguments);
  };

  debug = function() {
    if (log_level < 2) {
      return;
    }
    return console.log.apply(console, arguments);
  };

  trace = function() {
    if (log_level < 3) {
      return;
    }
    return console.log.apply(console, arguments);
  };

  error = function() {
    var lines, newError;
    newError = new Error;
    if (newError.stack != null) {
      lines = newError.stack.split("\n");
      console.log("Error", lines[2].trim());
    }
    return console.log.apply(console, arguments);
  };

  module.exports = {
    level: level,
    info: info,
    debug: debug,
    error: error,
    trace: trace,
    say: say
  };

}).call(this);
