// Generated by CoffeeScript 1.6.1
(function() {
  var EventEmitter, Resource, ResourceList, cat, fs, log, ls, path, processor, resourcelist, test, _, _ref;

  path = require('path');

  fs = require('fs');

  _ = require('./util');

  processor = require('./processor');

  log = require('./log');

  _ref = require('shelljs'), ls = _ref.ls, cat = _ref.cat, test = _ref.test;

  EventEmitter = require('events').EventEmitter;

  Resource = (function() {

    function Resource(filepath, content) {
      this.filepath = filepath;
      this.content = content;
      log.debug(" -", this.filepath);
      this.disable = false;
      this.ext = path.extname(this.filepath);
      this.type = this.ext.slice(1);
      this.target = processor.targetOf(this.filepath);
      this.path = this.filepath.replace(this.ext, '');
    }

    return Resource;

  })();

  ResourceList = (function() {

    ResourceList.fromPath = function(sourcePath) {
      var contents, filename, filepath, fileset, res, reslist, _i, _len;
      log.debug("Resources loaded from", sourcePath);
      reslist = new ResourceList;
      sourcePath = path.resolve(sourcePath);
      fileset = ls('-R', sourcePath);
      for (_i = 0, _len = fileset.length; _i < _len; _i++) {
        filename = fileset[_i];
        filepath = path.join(sourcePath, filename);
        if (!test('-f', filepath)) {
          continue;
        }
        contents = cat(filepath);
        res = new Resource(filename, contents);
        reslist.add(res);
      }
      return reslist;
    };

    function ResourceList() {
      this.tree = {};
      this.length = 0;
    }

    ResourceList.prototype.each = function(callback) {
      var i, key, resource, _ref1;
      i = 0;
      _ref1 = this.tree;
      for (key in _ref1) {
        resource = _ref1[key];
        callback(resource, i++);
      }
      return this;
    };

    ResourceList.prototype.forTarget = function(target) {
      var key, resource, _ref1, _results;
      _ref1 = this.tree;
      _results = [];
      for (key in _ref1) {
        resource = _ref1[key];
        if (resource.target === target) {
          _results.push(resource);
        }
      }
      return _results;
    };

    ResourceList.prototype.eachForTarget = function(target, callback) {
      var i, key, resource, _ref1;
      i = 0;
      _ref1 = this.tree;
      for (key in _ref1) {
        resource = _ref1[key];
        if (resource.target === target) {
          callback(resource, i++);
        }
      }
      return this;
    };

    ResourceList.prototype.add = function(resource) {
      if (this.tree[resource.path] != null) {
        log.info("Warning: redefining module '" + resource.path + "'");
      }
      this.tree[resource.path] = resource;
      this.length += 1;
      return this;
    };

    return ResourceList;

  })();

  resourcelist = function(filepath) {
    return ResourceList.fromPath(filepath);
  };

  module.exports = {
    Resource: Resource,
    ResourceList: ResourceList,
    resourcelist: resourcelist
  };

}).call(this);
