// Generated by CoffeeScript 1.6.1
(function() {
  var assembot, express, fs, loadOptions, log, path, _, _ref;

  _ = require('./util');

  fs = require('fs');

  log = require('./log');

  path = require('path');

  express = require('express');

  _ref = require('./index'), assembot = _ref.assembot, loadOptions = _ref.loadOptions;

  exports.start = function(bots, options) {
    return log.info("Starting server... (coming soon)");
  };

}).call(this);
