// Generated by CoffeeScript 1.5.0

/*
 AssemBot CLI!
*/


(function() {
  var assbot, default_conf, default_opts, path;

  path = require('path');

  assbot = require('./builder');

  default_conf = {
    "public/app.js": {
      source: './source',
      ident: 'public'
    },
    "public/theme.css": {
      source: './source'
    }
  };

  default_opts = {
    coffee: {
      bare: true
    }
  };

  module.exports = {
    run: function() {
      var assbot_conf, empty, here, nfo;
      here = process.cwd();
      nfo = (function() {
        try {
          return require("" + here + path.sep + "package");
        } catch (ex) {
          console.log("No 'package.json' file found, using defaults!");
          return empty = {
            assembot: default_conf
          };
        }
      })();
      assbot_conf = nfo.assembot == null ? (console.log("No 'assembot' block in your package.json file found, using defaults!"), default_conf) : nfo.assembot;
      return assbot.build(assbot_conf);
    }
  };

}).call(this);
