// Generated by CoffeeScript 1.5.0

/*
 AssemBot CLI!
*/


(function() {
  var builder, defaults, fs, optparse, path, server, _;

  path = require('path');

  fs = require('fs');

  _ = require('./util');

  builder = require('./builder');

  server = require('./server');

  defaults = require('./defaults');

  optparse = require('optparse');

  module.exports = {
    run: function() {
      var assbot_conf, assembot_info, buildTo, command, config, empty, nfo, options, parser, project_root, template;
      command = 'help';
      buildTo = {
        source: null,
        js: null,
        css: null
      };
      project_root = process.cwd();
      assembot_info = require('../package');
      nfo = (function() {
        try {
          return require("" + project_root + path.sep + "package");
        } catch (ex) {
          _.puts("No 'package.json' file found, using defaults!");
          return empty = {
            assembot: _.extend({}, defaults.assembot)
          };
        }
      })();
      assbot_conf = nfo.assembot == null ? (_.puts("No 'assembot' block in your package.json file found, using defaults!"), _.extend({}, defaults.assembot)) : nfo.assembot;
      options = _.defaults({}, assbot_conf.options || {}, defaults.options);
      delete assbot_conf.options;
      parser = new optparse.OptionParser([['-b', '--build', 'Run build'], ['-s', '--serve', 'Run dev server'], ['-f', '--files', 'Shows the build targets and associated files'], ['-d', '--debug', 'Shows internal build config data'], ['-p', '--port [PORT]', "Set dev server port"], ['-r', '--root [PATH]', 'Set dev server root path'], ['-m', '--minify [LEVEL]', 'Force minification 0=none 1=minify 2=mangle'], ['-c', '--modules', 'Shows the commonjs modules for .js build targets'], ['-v', '--version', 'Shows version number'], ['-h', '--help', 'Shows help'], ['--init', 'Creates a package.json, if missing'], ['--source [PATH]', 'Set source folder'], ['--js [PATH]', 'Export js package from source'], ['--css [PATH]', 'Export css package from source']]);
      parser.banner = 'Usage: assembot [options]';
      parser.on('build', function(name, value) {
        return command = name;
      });
      parser.on('help', function(name, value) {
        return command = name;
      });
      parser.on('debug', function(name, value) {
        return command = name;
      });
      parser.on('files', function(name, value) {
        return command = name;
      });
      parser.on('init', function(name, value) {
        return command = name;
      });
      parser.on('minify', function(name, value) {
        return options.minify = parseInt(value || "1");
      });
      parser.on('modules', function(name, value) {
        return command = name;
      });
      parser.on('port', function(name, value) {
        return options.port = value;
      });
      parser.on('serve', function(name, value) {
        return command = name;
      });
      parser.on('version', function(name, value) {
        return command = name;
      });
      parser.on('js', function(name, value) {
        return buildTo[name] = value;
      });
      parser.on('css', function(name, value) {
        return buildTo[name] = value;
      });
      parser.on('*', function(name, value) {
        return _.puts("Unknown option: " + name);
      });
      parser.on('root', function(name, value) {
        var newRoot;
        newRoot = path.resolve(value);
        if (fs.existsSync(newRoot)) {
          return options.wwwRoot = newRoot;
        } else {
          return _.log("Not a valid path: " + newRoot);
        }
      });
      parser.on('source', function(name, value) {
        command = name;
        return buildTo.source = value;
      });
      parser.parse(process.argv);
      if (command === 'serve') {
        return server.serve(assbot_conf, options);
      } else if (command === 'build') {
        return builder.build(assbot_conf, options);
      } else if (command === 'files') {
        return builder.displayTargetTree(assbot_conf, options);
      } else if (command === 'modules') {
        return builder.displayModuleTree(assbot_conf, options);
      } else if (command === 'debug') {
        builder.prepConfig(assbot_conf, options);
        return _.pp(assbot_conf);
      } else if (command === 'version') {
        return _.puts(assembot_info.version);
      } else if (command === 'init') {
        _.puts("ASSEMBOT! Bleep, bloop!\nv" + assembot_info.version + "\n");
        if (fs.existsSync('./package.json')) {
          return _.puts("package.json already exists.");
        } else {
          _.puts("Creating a default package.json for you...");
          assembot_conf.options = defaults.options;
          template = {
            name: path.basename(process.cwd()),
            version: "1.0.0",
            license: "",
            description: "",
            author: "",
            assembot: assbot_conf
          };
          fs.writeFileSync(path.resolve('./package.json'), JSON.stringify(template, null, 2));
          return _.puts('Done.');
        }
      } else if (command === 'source') {
        config = {};
        if (buildTo.js != null) {
          config[buildTo.js] = _.extend({}, defaults.config, {
            source: buildTo.source
          });
        }
        if (buildTo.css != null) {
          config[buildTo.css] = _.extend({}, defaults.config, {
            source: buildTo.source
          });
          return builder.build(config, options);
        }
      } else {
        _.puts("ASSEMBOT! Bleep, bloop!\nv" + assembot_info.version + "\n");
        return _.puts(parser.toString());
      }
    }
  };

}).call(this);
