// Generated by CoffeeScript 1.5.0
(function() {

  exports.config = {
    source: './source',
    ident: 'require',
    autoStart: false,
    minify: 0,
    header: "/* Assembled by Assembot {%- assembot.version -%} */",
    replaceTokens: true,
    coffee: {
      bare: true,
      literate: false
    }
  };

  exports.options = {
    port: 8080,
    wwwRoot: './public'
  };

  exports.assembot = {
    "public/app.js": exports.config,
    "public/theme.css": exports.config
  };

}).call(this);
