// Generated by CoffeeScript 1.5.0
(function() {
  var _;

  _ = require('./util');

  exports.config = {
    source: './source',
    ident: 'require',
    autoStart: false,
    minify: 0,
    sourceMap: false,
    header: "/* Assembled by AssemBot {%- assembot.version -%} */",
    replaceTokens: true,
    coffee: {
      bare: true,
      literate: false
    }
  };

  exports.options = {
    port: 8080,
    wwwRoot: './public'
  };

  exports.assembot = {
    "public/app.js": _.extend({}, exports.config),
    "public/theme.css": _.extend({}, exports.config)
  };

}).call(this);
