// Generated by CoffeeScript 1.6.1

/*
assembot:
  options:
    autoincrement:
      enabled: yes
      target: './package.json'
      segment: 'build' # or major, minor, patch
      when: 'after:write'
*/


(function() {
  var path, semver;

  semver = require('semver');

  path = require('path');

  module.exports = function(assembot, ident) {
    var log;
    ident("Increment Version");
    log = assembot.log;
    return assembot.on('done', function(options) {
      var filepath, output, pinfo;
      if (options.autoincrement == null) {
        return;
      }
      if (!(options.autoincrement.enabled === true || options.autoincrement.enable === true)) {
        return;
      }
      filepath = path.resolve(path.join(process.cwd(), options.autoincrement.target));
      pinfo = require(filepath);
      pinfo.version = semver.inc(pinfo.version, options.autoincrement.segment);
      log.info("Incrementing build version to", pinfo.version);
      output = JSON.stringify(pinfo, null, 2);
      return output.to(filepath);
    });
  };

}).call(this);
