// Generated by CoffeeScript 1.6.1
(function() {
  var do_minify, uglify;

  uglify = (function() {
    try {
      return require("uglify-js");
    } catch (ex) {
      return null;
    }
  })();

  do_minify = function(flag, output_content, log) {
    var settings;
    if (uglify != null) {
      log.debug("Minify...");
      try {
        settings = {
          fromString: true,
          mangle: false
        };
        switch (flag) {
          case 1:
          case 'minify':
          case 'min':
            return uglify.minify(output_content, settings);
          case 2:
          case 'mangle':
          case 'munge':
          case 'compress':
            settings.mangle = true;
            return uglify.minify(output_content, settings);
          default:
            return {
              code: output_content,
              map: null
            };
        }
      } catch (ex) {
        log.info("Error in minify, skipping...");
        log.error(ex);
        return {
          code: output_content,
          map: null
        };
      }
    } else {
      log.info("Can't minify (install uglify-js)...");
      return {
        code: output_content,
        map: null
      };
    }
  };

  module.exports = function(assembot, ident) {
    var log;
    log = assembot.log;
    return assembot.after('build', function(bot) {
      if (bot.target !== 'js') {
        return;
      }
      if ((bot.options.minify != null) && bot.options.minify !== false && bot.options.minify > 0) {
        return bot.content = do_minify(bot.options.minify, bot.content, log).code;
      }
    });
  };

}).call(this);
