// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(assembot) {
    var log;
    log = assembot.log;
    assembot.after('render', function(bot) {
      var res, _i, _len, _ref, _results;
      if (bot.target !== 'js') {
        return;
      }
      _ref = bot.resources;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        res = _ref[_i];
        _results.push(log.info(" - ", res.path));
      }
      return _results;
    });
    return assembot.before('write', function(bot) {
      if (bot.target !== 'js') {
        return;
      }
      return log.info("PRUNE DEPS");
    });
  };

}).call(this);
