// Generated by CoffeeScript 1.6.1
(function() {
  var _;

  _ = require('./util');

  exports.config = {
    source: './source',
    ident: 'require',
    autoStart: false,
    minify: 0,
    sourceMap: false,
    header: "/* Assembled by AssemBot {%- assembot.version -%} */",
    replaceTokens: true
  };

  exports.options = {
    port: 8080,
    wwwRoot: './public',
    http: {
      "/": "./public",
      "/components": "./components"
    }
  };

  exports.assembot = {
    "public/app.js": _.extend({}, exports.config),
    "public/theme.css": _.extend({}, exports.config)
  };

}).call(this);
